In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r'C:\Users\admin\Downloads\Weather.csv')

C:\Users\admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (7,8,18,24) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
# Problem Statement -based on maximum Temperature we have to predict minimum temperature

In [5]:
df.head()

STA      Date Precip  WindGustSpd    MaxTemp    MinTemp   MeanTemp  \
0  10001  7/1/1942  1.016          NaN  25.555556  22.222222  23.888889   
1  10001  7/2/1942      0          NaN  28.888889  21.666667  25.555556   
2  10001  7/3/1942   2.54          NaN  26.111111  22.222222  24.444444   
3  10001  7/4/1942   2.54          NaN  26.666667  22.222222  24.444444   
4  10001  7/5/1942      0          NaN  26.666667  21.666667  24.444444   

  Snowfall PoorWeather  YR  ...  FT  FB FTI  PGT  TSHDSBRSGF  SD3  RHX  RHN  \
0      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
1      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
2      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
3      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
4      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   

  RVG  WTE  
0 NaN  NaN  
1 NaN  NaN  
2 NaN  NaN  
3 NaN  NaN  
4 NaN  NaN  

[5 rows x 30 columns]

In [6]:
df.describe()

STA  WindGustSpd        MaxTemp        MinTemp  \
count  119040.000000   532.000000  119040.000000  119040.000000   
mean    29659.435795    37.774534      27.045111      17.789511   
std     20953.209402    10.297808       8.717817       8.334572   
min     10001.000000    18.520000     -33.333333     -38.333333   
25%     11801.000000    29.632000      25.555556      15.000000   
50%     22508.000000    37.040000      29.444444      21.111111   
75%     33501.000000    43.059000      31.666667      23.333333   
max     82506.000000    75.932000      50.000000      34.444444   

            MeanTemp             YR             MO             DA          DR  \
count  119040.000000  119040.000000  119040.000000  119040.000000  533.000000   
mean       22.411631      43.805284       6.726016      15.797530   26.998124   
std         8.297982       1.136718       3.425561       8.794541   15.221732   
min       -35.555556      40.000000       1.000000       1.000000    2.000000   
25%        20.555556      43.000000       4.000000       8.000000   11.000000   
50%        25.555556      44.000000       7.000000      16.000000   32.000000   
75%        27.222222      45.000000      10.000000      23.000000   34.000000   
max        40.000000      45.000000      12.000000      31.000000   78.000000   

              SPD  ...     SND   FT   FB  FTI         PGT  SD3  RHX  RHN  RVG  \
count  532.000000  ...  5563.0  0.0  0.0  0.0  525.000000  0.0  0.0  0.0  0.0   
mean    20.396617  ...     0.0  NaN  NaN  NaN   12.085333  NaN  NaN  NaN  NaN   
std      5.560371  ...     0.0  NaN  NaN  NaN    5.731328  NaN  NaN  NaN  NaN   
min     10.000000  ...     0.0  NaN  NaN  NaN    0.000000  NaN  NaN  NaN  NaN   
25%     16.000000  ...     0.0  NaN  NaN  NaN    8.500000  NaN  NaN  NaN  NaN   
50%     20.000000  ...     0.0  NaN  NaN  NaN   11.600000  NaN  NaN  NaN  NaN   
75%     23.250000  ...     0.0  NaN  NaN  NaN   15.000000  NaN  NaN  NaN  NaN   
max     41.000000  ...     0.0  NaN  NaN  NaN   23.900000  NaN  NaN  NaN  NaN   

       WTE  
count  0.0  
mean   NaN  
std    NaN  
min    NaN  
25%    NaN  
50%    NaN  
75%    NaN  
max    NaN  

[8 rows x 23 columns]

In [7]:
#independent variable/
x=df[['MaxTemp']]
x.head()

MaxTemp
0  25.555556
1  28.888889
2  26.111111
3  26.666667
4  26.666667

In [8]:
#dependent variable/feature/parameter/column
y=df[['MinTemp']]

In [9]:
y.head()

MinTemp
0  22.222222
1  21.666667
2  22.222222
3  22.222222
4  21.666667

In [10]:
x=x.values.reshape(-1,1)
x

array([[25.55555556],
       [28.88888889],
       [26.11111111],
       ...,
       [28.33333333],
       [28.33333333],
       [29.44444444]])

In [11]:
y=y.values.reshape(-1,1)
y

array([[22.22222222],
       [21.66666667],
       [22.22222222],
       ...,
       [18.33333333],
       [18.33333333],
       [17.22222222]])

In [12]:
x

array([[25.55555556],
       [28.88888889],
       [26.11111111],
       ...,
       [28.33333333],
       [28.33333333],
       [29.44444444]])

In [13]:
y

array([[22.22222222],
       [21.66666667],
       [22.22222222],
       ...,
       [18.33333333],
       [18.33333333],
       [17.22222222]])

In [14]:
# train_test_split
from sklearn.model_selection import train_test_split

In [15]:
#spliting of data
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,test_size=0.3)

In [16]:
x_train.shape

(83328, 1)

In [17]:
x_test.shape

(35712, 1)

In [18]:
y_train.shape

(83328, 1)

In [19]:
y_test.shape

(35712, 1)

In [20]:
# Importing lenear regression
from sklearn.linear_model import LinearRegression

In [21]:
#object Creation
model=LinearRegression()

In [22]:
# Training the model using the .fit()function
model.fit(x_train,y_train)

LinearRegression()

In [23]:
# testing the data/model or prediction the data or predicting the model
y_pred=model.predict(x_test)
y_pred

array([[23.99950559],
       [ 5.37022474],
       [-2.54721962],
       ...,
       [14.21913315],
       [18.41072134],
       [13.28766911]])

In [24]:
from sklearn.metrics import r2_score

In [25]:
r2_score(y_test,y_pred)*100

77.61273490695532

In [26]:
#alternate method
model.score(x_test,y_test)*100

77.61273490695532

In [27]:
model.score(x_train,y_train)

0.7695457933615968

In [28]:
adj_r2_score = 1-(1-model.score(x_test,y_test))*len((y_train)-1)/(len(y_train)-y_test.shape[1]-1)
adj_r2_score

0.7761219756530703

In [29]:
adj_r2_score*100

77.61219756530703

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
mean_squared_error(y_test,y_pred)

15.799714098891027